SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `lotomidas` DEFAULT CHARACTER SET latin1 ;
USE `lotomidas` ;

-- -----------------------------------------------------
-- Table `lotomidas`.`lotofacil`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `lotomidas`.`lotofacil` (
  `b1` INT(11) NULL DEFAULT NULL ,
  `b2` INT(11) NULL DEFAULT NULL ,
  `b3` INT(11) NULL DEFAULT NULL ,
  `b4` INT(11) NULL DEFAULT NULL ,
  `b5` INT(11) NULL DEFAULT NULL ,
  `b6` INT(11) NULL DEFAULT NULL ,
  `b7` INT(11) NULL DEFAULT NULL ,
  `b8` INT(11) NULL DEFAULT NULL ,
  `b9` INT(11) NULL DEFAULT NULL ,
  `b10` INT(11) NULL DEFAULT NULL ,
  `b11` INT(11) NULL DEFAULT NULL ,
  `b12` INT(11) NULL DEFAULT NULL ,
  `b13` INT(11) NULL DEFAULT NULL ,
  `b14` INT(11) NULL DEFAULT NULL ,
  `b15` INT(11) NULL DEFAULT NULL ,
  `rateio15` FLOAT NULL DEFAULT NULL ,
  `rateio14` FLOAT NULL DEFAULT NULL ,
  `rateio13` FLOAT NULL DEFAULT NULL ,
  `rateio12` FLOAT NULL DEFAULT NULL ,
  `rateio11` FLOAT NULL DEFAULT NULL ,
  `ganhadores15` INT(11) NULL DEFAULT NULL ,
  `ganhadores14` INT(11) NULL DEFAULT NULL ,
  `ganhadores13` INT(11) NULL DEFAULT NULL ,
  `ganhadores12` INT(11) NULL DEFAULT NULL ,
  `ganhadores11` INT(11) NULL DEFAULT NULL ,
  `estimativa` FLOAT NULL DEFAULT NULL ,
  `acumulado15` FLOAT NULL DEFAULT NULL ,
  `data_sorteio` DATETIME NULL DEFAULT NULL ,
  `arrecadacao` FLOAT NULL DEFAULT NULL ,
  `concurso` INT(11) NOT NULL ,
  PRIMARY KEY (`concurso`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
